# Generated by Django 5.1.5 on 2025-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
